### ISSUE TITLE
Avoid mangling integers when pickling sage integers

### ISSUE THREAD

**Issue by florian-rabe** [OpenDreamKit/MitM-Sage#2]
@nthiery 

What has to be done to export Sage integers as
OMA(sage_integer, AN ACTUAL INTEGER AND NOT A STRING ENCODING) ?

**Comment by nthiery** [comment]
>    What has to be done to export Sage integers as
>    OMA(sage_integer, AN ACTUAL INTEGER AND NOT A STRING ENCODING) ?

Hmm I don't know without changing the Sage sources actually.
Introducing a special converter for the class Integer does not work
since it won't be called when converting a Sage integer embedded into
a larger object.

So instead, we would need to change how to pickle Sage integers; pickling
is currently implemented by the following method of `Integer`:
```
sage: i = 1
sage: i.__reduce__??
Source:
    def __reduce__(self):
        """
        This is used when pickling integers.

        EXAMPLES::

            sage: n = 5
            sage: t = n.__reduce__(); t
            (<cyfunction make_integer at ...>, ('5',))
            sage: t[0](*t[1])
            5
            sage: loads(dumps(n)) == n
            True
        """
        # This single line below took me HOURS to figure out.
        # It is the *trick* needed to pickle Cython extension types.
        # The trick is that you must put a pure Python function
        # as the first argument, and that function must return
        # the result of unpickling with the argument in the second
        # tuple as input. All kinds of problems happen
        # if we don't do this.
        return sage.rings.integer.make_integer, (self.str(32),)
```
But since Integer is a Cython (compiled) class, we can't monkey patch
it dynamically.

Maybe we can tweak openmath_pickle to detect certain subformulae and
replace them, but this seems rather hacky.

**Comment by florian-rabe** [comment]
@nthiery So integers embedded in larger objects never go through our OpenMath converter?

If that's the case, I only see post-processing as an option: traverse the OpenMath to find any o of the form OMA(make_interger, string) convert it to Python, extract the integer i, and replace o with OMI(i).
Would that work?

**Comment by nthiery** [comment]
>    [1]@nthiery So integers embedded in larger objects never go through our
>    OpenMath converter?

Yup. The OpenMath converter starts its work from the pickle, where the
integer has already been transformed in a make_integer. That's the
main limitation of the approach.

Ah ah, but digging into Python's pickling code, I actually found some
support to add hooks for "C" classes for which we can't configure
pickling by overriding (monkey patching) the `__reduce__` method:


```
sage: explain_pickle(dumps(1))
pg_make_integer = unpickle_global('sage.rings.integer', 'make_integer')
pg_make_integer('1')
sage: explain_pickle(dumps(10))
pg_make_integer = unpickle_global('sage.rings.integer', 'make_integer')
pg_make_integer('a')
sage: import copyreg
sage: def pickle_sage_integer(i):
....:     return Integer, (int(i),)
....: 
sage: copyreg.pickle(Integer, pickle_sage_integer)
sage: explain_pickle(dumps(10))
pg_Integer = unpickle_global('sage.rings.integer', 'Integer')
pg_Integer(10r)
sage: 

```

So, we are good to go for our application.
```
sage: import openmath.convert_pickle
sage: openmath.convert_pickle.to_openmath(10)
OMApplication(elem=OMSymbol(name='Integer', cd='sage.rings.integer', id=None, cdbase='http://python.org'), arguments=[OMInteger(integer=10, id=None)], id=None, cdbase=None)
```

Presumably we can do the same for polynomials.

**Comment by florian-rabe** [comment]
I've added Nicolas's fix to https://github.com/OpenDreamKit/MitM-Sage/blob/master/sage/converting_server.py
